{% set version = "2.2.2" %}

package:
  name: r-r6
  version: {{ version }}

source:
  fn: R6_{{ version }}.tar.gz
  url:
    - http://cran.r-project.org/src/contrib/R6_{{ version }}.tar.gz
    - http://cran.r-project.org/src/contrib/Archive/R6/R6_{{ version }}.tar.gz
  sha256: 087756f471884c3b3ead80215a7cc5636a78b8a956e91675acfe2896426eae8f

build:
  number: 0
  skip: True  # [win32]
  script: R CMD INSTALL --build .
  rpaths:
    - lib/R/lib/
    - lib/

requirements:  # [not win32]
  build:  # [not win32]
    - r-base  # [not win32]
  run:  # [not win32]
    - r-base  # [not win32]

test:
  commands:
    - R -e "library('R6')"  # [not win]
    - R -e \"library('R6')\"  # [win]

about:
  home: https://github.com/wch/R6/
  license: MIT
  license_file: LICENSE
  summary: "The R6 package allows the creation of classes with reference semantics, similar to
    R's built-in reference classes. Compared to reference classes, R6 classes are simpler
    and lighter-weight, and they are not built on S4 classes so they do not require
    the methods package. These classes allow public and private members, and they support
    inheritance, even when the classes are defined in different packages."

extra:
  recipe-maintainers:
    - ocefpaf
